name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: vcpkg install protobuf protobuf:x64-windows
      
    - name: Generate C++ code
      shell: cmd
      run: |
        mkdir upload
        dir C:\vcpkg
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
