name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        git checkout 6245ce4 -- ports/protobuf
        vcpkg install protobuf protobuf:x64-windows-static

    - name: List all files
      shell: cmd
      run: dir ${{github.workspace}}\vcpkg /s
        
    - name: Copy over the files
      shell: cmd
      run: |
        mkdir upload
        mkdir upload\bin
        mkdir upload\include
        mkdir upload\include\google
        mkdir upload\lib
        mkdir upload\share
        copy /y /v ${{github.workspace}}\vcpkg\installed\x64-windows-static\tools\protobuf\protoc.exe upload\bin
        xcopy /y /v /s /e ${{github.workspace}}\vcpkg\installed\x64-windows-static\include\google upload\include\google
        copy /y /v ${{github.workspace}}\vcpkg\installed\x64-windows-static\lib\lib*.lib upload\lib
        copy /y /v ${{github.workspace}}\vcpkg\installed\x64-windows-static\debug\lib\lib*.lib upload\lib
        copy /y /v ${{github.workspace}}\vcpkg\installed\x64-windows-static\share\protobuf\*.* upload\share

    - name: Generate C++ files
      shell: cmd
      run: |
        mkdir upload\cpp-files
        ${{github.workspace}}\vcpkg\installed\x64-windows-static\tools\protobuf\protoc.exe --cpp_out=upload\cpp-files widevine_protocol.proto

    - name: Upload triplets
      uses: actions/upload-artifact@v4
      with:
        name: Triplets-artifact
        path: ${{github.workspace}}/vcpkg/triplets
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
        
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package-artifact
        path: ${{github.workspace}}\vcpkg\packages\protobuf_x64-windows-static
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
